### PR TITLE
added entry snippets and e-mail functionality, no styling yet

### PR DESCRIPTION
**Pull request by C-Stein**
Basic career dev homepage is done without styling.

### CODE REVIEW

**Comment by NewEvolution** [comment]
contact.html and job-page.html would prefer a newline at the end of the file, otherwise :+1:

**Comment by C-Stein** [comment]
Just a blank line?

**Comment by NewEvolution** [comment]
Yep.  It's a convention and Github highlights it with an angry red :do_not_litter: sign in the files changed tab, which is the only reason I even noticed it.

Also, if you're using Sublime, there's a plugin that auto-adds a newline on save.

**Comment by C-Stein** [comment]
OK, new lines have been added (any idea why that is convention?) I also added a job posting template, and a couple of files (way more than should be necessary) to make sure the image in the navbar shows up on the  posts.

**Comment by NewEvolution** [comment]
Looks good.  The convention is [because without a newline at the end, the line technically doesn't _actually_ end](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

**Pull request merged**
